---
title: "CaDrA Query of BRCA YAP/TAZ Activity"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CaDrA Query of BRCA YAP/TAZ Activity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE, messages=FALSE, warnings=FALSE}
knitr::opts_chunk$set(comment="", cache=FALSE, fig.width=8, fig.align="center")
library(tidyverse)
devtools::load_all(".")
```

Here, we reproduce the results of Figure 5 of [[Kartha et al., 2019]](https://www.frontiersin.org/articles/10.3389/fgene.2019.00121/full) (the section titled "_CaDrA Reveals Novel Drivers of Oncogenic YAP/TAZ Activity in Human Breast Cancer_").

```{r settings, echo=FALSE}
library(Biobase)
library(CaDrA)
library(tidyverse)
library(ggplot2)
```

## Upload & format data inputs
```{r load.data}

## Read in BRCA GISTIC+Mutation ESet object
data(BRCA_GISTIC_MUT_SIG)
eset_mut_scna <- BRCA_GISTIC_MUT_SIG

## Read in input score
data(TAZYAP_BRCA_ACTIVITY)
input_scores <- TAZYAP_BRCA_ACTIVITY

## Samples to keep based on the overlap between the two inputs
overlap <- intersect(names(input_scores), Biobase::sampleNames(eset_mut_scna))
eset_mut_scna <- eset_mut_scna[,overlap]
input_scores <- input_scores[overlap]

## Binarize ES to only have 0's and 1's
exprs(eset_mut_scna)[exprs(eset_mut_scna)>1] <- 1.0

## Pre-filter ESet based on occurrence frequency
eset_mut_scna_flt <- prefilter_data(
  ES = eset_mut_scna,
  max.cutoff = 0.6, # max frequency (60%)
  min.cutoff = 0.03 # min frequency (3%)
) 

```

## Run CaDrA

```{r cadra}
topn_res <- topn_eval(
  ES = eset_mut_scna_flt,
  input_score = input_scores,
  method="ks",             # ks-based feature scoring
  top_N = 7,               # Evaluate top 7 starting points for the search
  do_plot = FALSE,         # we'll plot later
  best_score_only = FALSE,
  verbose = FALSE
)
```

## Visualize best result
```{r visualize.best}
## Fetch the ESet and feature set corresponding to best score over the top_N searches
topn_best_meta <- topn_best(topn_res)
# Visualize best results using the function meta_plot
meta_plot(topn_best_list = topn_best_meta)
```

## Summarize top_N results

```{r summarize}
# Evaluate results across top_N seed features you started from
topn_plot(topn_res) 
```